# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Hands Inc :: innovative holistic health solutions, complementary therapies, health awareness workshops and training'
email: handsinc@handsinc.co.uk
description: > # this means to ignore newlines until "baseurl:"
  innovative holistic health solutions, complementary therapies, health
  awareness workshops and training
baseurl: '' # the subpath of your site, e.g. /blog
url: http://handsinc.co.uk # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# collections:
#   services:
#     output: true
#     permalink: /services/:path/
menus:
  side:
    - Home: /
    - About Us:
      - /aboutus/
      - Our Work in the Community: /aboutus/#community
      - Our Work with Employers & Staff: /aboutus/#employers
      - What We Believe: /aboutus/#believe
      - Testimonials: /aboutus/#testimonials
    - Services:
      - /services/
      - Complementing Your Health: /services/complementing-your-health/
      - Complementary Therapies:
        - /services/complementary-therapies/
        - Range of Therapies: /services/complementary-therapies/#therapies
      - Menopause Project:
        - /services/menopause-project/
        - Support Group: /services/menopause-project/support-group/
      - Healthy Lifestyle Activities: /services/healthy-lifestyle-activities/
      - Move & Release: /services/move-and-release/
      - Stress Awareness: /services/stress-awareness/
    - Wellbeing @ Work:
      - /wellbeing-at-work/
      - Massage @ Work: /wellbeing-at-work/massage-at-work/
    - Healthwise Directory:
      - /healthwise-directory/
      - About Hands Inc: /healthwise-directory/about-handsinc/
      - Hands Inc Services:
        - /healthwise-directory/handsinc-services/
        - Low Cost Massage Clinic: /healthwise-directory/handsinc-services/#clinic
        - Healthwise Outreach Programme: /healthwise-directory/handsinc-services/#healthwise
        - Stress Awareness Programmes: /healthwise-directory/handsinc-services/#stress
        - Outreach Complementary Therapy: /healthwise-directory/handsinc-services/#outreach
      - Physical Wellbeing:
        - /healthwise-directory/physical-wellbeing/
        - French: /healthwise-directory/physical-wellbeing/french/
        - Turkish: /healthwise-directory/physical-wellbeing/turkish/
        - Vietnamese: /healthwise-directory/physical-wellbeing/vietnamese/
      - Social Wellbeing:
        - /healthwise-directory/social-wellbeing/
        - French: /healthwise-directory/social-wellbeing/french/
        - Turkish: /healthwise-directory/social-wellbeing/turkish/
        - Vietnamese: /healthwise-directory/social-wellbeing/vietnamese/
      - Mental & Emotional Wellbeing:
        - /healthwise-directory/mental-and-emotional-wellbeing/
        - French: /healthwise-directory/mental-and-emotional-wellbeing/french/
        - Turkish: /healthwise-directory/mental-and-emotional-wellbeing/turkish/
        - Vietnamese: /healthwise-directory/mental-and-emotional-wellbeing/vietnamese/
      - Culturally Specific Services:
        - /healthwise-directory/culturally-specific-services/
        - French: /healthwise-directory/culturally-specific-services/french/
        - Turkish: /healthwise-directory/culturally-specific-services/turkish/
        - Vietnamese: /healthwise-directory/culturally-specific-services/vietnamese/
      - Advice & Support:
        - /healthwise-directory/advice-and-support/
        - French: /healthwise-directory/advice-and-support/french/
        - Turkish: /healthwise-directory/advice-and-support/turkish/
        - Vietnamese: /healthwise-directory/advice-and-support/vietnamese/
      - Employment:
        - /healthwise-directory/employment/
        - French: /healthwise-directory/employment/french/
        - Turkish: /healthwise-directory/employment/turkish/
        - Vietnamese: /healthwise-directory/employment/vietnamese/
    - Get Involved: /get-involved/
    - Contact Us: /contact-us/

exclude:
  - bin/*
  - Gemfile
  - Gemfile.lock
  - vendor/
  - kickster/
  - _images/

# Build settings
# markdown: kramdown
